/* eslint-disable no-unused-vars */
export enum TCountryCode {
  NULL = '',
  AD = 'AD',
  AE = 'AE',
  AF = 'AF',
  AG = 'AG',
  AI = 'AI',
  AL = 'AL',
  AM = 'AM',
  AO = 'AO',
  AQ = 'AQ',
  AR = 'AR',
  AS = 'AS',
  AT = 'AT',
  AU = 'AU',
  AW = 'AW',
  AX = 'AX',
  AZ = 'AZ',
  BA = 'BA',
  BB = 'BB',
  BD = 'BD',
  BE = 'BE',
  BF = 'BF',
  BG = 'BG',
  BH = 'BH',
  BI = 'BI',
  BJ = 'BJ',
  BL = 'BL',
  BM = 'BM',
  BN = 'BN',
  BO = 'BO',
  BR = 'BR',
  BS = 'BS',
  BT = 'BT',
  BV = 'BV',
  BW = 'BW',
  BY = 'BY',
  BZ = 'BZ',
  CA = 'CA',
  CC = 'CC',
  CD = 'CD',
  CF = 'CF',
  CG = 'CG',
  CH = 'CH',
  CI = 'CI',
  CK = 'CK',
  CL = 'CL',
  CM = 'CM',
  CN = 'CN',
  CO = 'CO',
  CR = 'CR',
  CU = 'CU',
  CV = 'CV',
  CW = 'CW',
  CX = 'CX',
  CY = 'CY',
  CZ = 'CZ',
  DE = 'DE',
  DJ = 'DJ',
  DK = 'DK',
  DM = 'DM',
  DO = 'DO',
  DZ = 'DZ',
  EC = 'EC',
  EE = 'EE',
  EG = 'EG',
  EH = 'EH',
  ER = 'ER',
  ES = 'ES',
  ET = 'ET',
  FI = 'FI',
  FJ = 'FJ',
  FK = 'FK',
  FM = 'FM',
  FO = 'FO',
  FR = 'FR',
  GA = 'GA',
  GB = 'GB',
  GD = 'GD',
  GE = 'GE',
  GF = 'GF',
  GG = 'GG',
  GH = 'GH',
  GI = 'GI',
  GL = 'GL',
  GM = 'GM',
  GN = 'GN',
  GP = 'GP',
  GQ = 'GQ',
  GR = 'GR',
  GS = 'GS',
  GT = 'GT',
  GU = 'GU',
  GW = 'GW',
  GY = 'GY',
  HK = 'HK',
  HM = 'HM',
  HN = 'HN',
  HR = 'HR',
  HT = 'HT',
  HU = 'HU',
  ID = 'ID',
  IE = 'IE',
  IL = 'IL',
  IM = 'IM',
  IN = 'IN',
  IO = 'IO',
  IQ = 'IQ',
  IR = 'IR',
  IS = 'IS',
  IT = 'IT',
  JE = 'JE',
  JM = 'JM',
  JO = 'JO',
  JP = 'JP',
  KE = 'KE',
  KG = 'KG',
  KH = 'KH',
  KI = 'KI',
  KM = 'KM',
  KN = 'KN',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KY = 'KY',
  KZ = 'KZ',
  LA = 'LA',
  LB = 'LB',
  LC = 'LC',
  LI = 'LI',
  LK = 'LK',
  LR = 'LR',
  LS = 'LS',
  LT = 'LT',
  LU = 'LU',
  LV = 'LV',
  LY = 'LY',
  MA = 'MA',
  MC = 'MC',
  MD = 'MD',
  ME = 'ME',
  MF = 'MF',
  MG = 'MG',
  MH = 'MH',
  MK = 'MK',
  ML = 'ML',
  MM = 'MM',
  MN = 'MN',
  MO = 'MO',
  MP = 'MP',
  MQ = 'MQ',
  MR = 'MR',
  MS = 'MS',
  MT = 'MT',
  MU = 'MU',
  MV = 'MV',
  MW = 'MW',
  MX = 'MX',
  MY = 'MY',
  MZ = 'MZ',
  NA = 'NA',
  NC = 'NC',
  NE = 'NE',
  NF = 'NF',
  NG = 'NG',
  NI = 'NI',
  NL = 'NL',
  NO = 'NO',
  NP = 'NP',
  NR = 'NR',
  NU = 'NU',
  NZ = 'NZ',
  OM = 'OM',
  PA = 'PA',
  PE = 'PE',
  PF = 'PF',
  PG = 'PG',
  PH = 'PH',
  PK = 'PK',
  PL = 'PL',
  PM = 'PM',
  PN = 'PN',
  PR = 'PR',
  PS = 'PS',
  PT = 'PT',
  PW = 'PW',
  PY = 'PY',
  QA = 'QA',
  RE = 'RE',
  RO = 'RO',
  RS = 'RS',
  RU = 'RU',
  RW = 'RW',
  SA = 'SA',
  SB = 'SB',
  SC = 'SC',
  SD = 'SD',
  SE = 'SE',
  SG = 'SG',
  SH = 'SH',
  SI = 'SI',
  SJ = 'SJ',
  SK = 'SK',
  SL = 'SL',
  SM = 'SM',
  SN = 'SN',
  SO = 'SO',
  SR = 'SR',
  SS = 'SS',
  ST = 'ST',
  SV = 'SV',
  SX = 'SX',
  SY = 'SY',
  SZ = 'SZ',
  TC = 'TC',
  TD = 'TD',
  TF = 'TF',
  TG = 'TG',
  TH = 'TH',
  TJ = 'TJ',
  TK = 'TK',
  TL = 'TL',
  TM = 'TM',
  TN = 'TN',
  TO = 'TO',
  TR = 'TR',
  TT = 'TT',
  TV = 'TV',
  TW = 'TW',
  TZ = 'TZ',
  UA = 'UA',
  UG = 'UG',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VA = 'VA',
  VC = 'VC',
  VE = 'VE',
  VG = 'VG',
  VI = 'VI',
  VN = 'VN',
  VU = 'VU',
  WF = 'WF',
  WS = 'WS',
  XK = 'XK',
  YE = 'YE',
  YT = 'YT',
  ZA = 'ZA',
  ZM = 'ZM',
  ZW = 'ZW',
}

export const CCountries: Array<{
  value: TCountryCode;
  phone: string;
  label: string;
  suggested?: boolean;
}> = [
  { value: TCountryCode['AD'], label: 'Andorra', phone: '376' },
  {
    value: TCountryCode['AE'],
    label: 'United Arab Emirates',
    phone: '971',
  },
  { value: TCountryCode['AF'], label: 'Afghanistan', phone: '93' },
  {
    value: TCountryCode['AG'],
    label: 'Antigua and Barbuda',
    phone: '1-268',
  },
  { value: TCountryCode['AI'], label: 'Anguilla', phone: '1-264' },
  { value: TCountryCode['AL'], label: 'Albania', phone: '355' },
  { value: TCountryCode['AM'], label: 'Armenia', phone: '374' },
  { value: TCountryCode['AO'], label: 'Angola', phone: '244' },
  { value: TCountryCode['AQ'], label: 'Antarctica', phone: '672' },
  { value: TCountryCode['AR'], label: 'Argentina', phone: '54' },
  { value: TCountryCode['AS'], label: 'American Samoa', phone: '1-684' },
  { value: TCountryCode['AT'], label: 'Austria', phone: '43' },
  {
    value: TCountryCode['AU'],
    label: 'Australia',
    phone: '61',
    suggested: true,
  },
  { value: TCountryCode['AW'], label: 'Aruba', phone: '297' },
  { value: TCountryCode['AX'], label: 'Alland Islands', phone: '358' },
  { value: TCountryCode['AZ'], label: 'Azerbaijan', phone: '994' },
  {
    value: TCountryCode['BA'],
    label: 'Bosnia and Herzegovina',
    phone: '387',
  },
  { value: TCountryCode['BB'], label: 'Barbados', phone: '1-246' },
  { value: TCountryCode['BD'], label: 'Bangladesh', phone: '880' },
  { value: TCountryCode['BE'], label: 'Belgium', phone: '32' },
  { value: TCountryCode['BF'], label: 'Burkina Faso', phone: '226' },
  { value: TCountryCode['BG'], label: 'Bulgaria', phone: '359' },
  { value: TCountryCode['BH'], label: 'Bahrain', phone: '973' },
  { value: TCountryCode['BI'], label: 'Burundi', phone: '257' },
  { value: TCountryCode['BJ'], label: 'Benin', phone: '229' },
  { value: TCountryCode['BL'], label: 'Saint Barthelemy', phone: '590' },
  { value: TCountryCode['BM'], label: 'Bermuda', phone: '1-441' },
  { value: TCountryCode['BN'], label: 'Brunei Darussalam', phone: '673' },
  { value: TCountryCode['BO'], label: 'Bolivia', phone: '591' },
  { value: TCountryCode['BR'], label: 'Brazil', phone: '55' },
  { value: TCountryCode['BS'], label: 'Bahamas', phone: '1-242' },
  { value: TCountryCode['BT'], label: 'Bhutan', phone: '975' },
  { value: TCountryCode['BV'], label: 'Bouvet Island', phone: '47' },
  { value: TCountryCode['BW'], label: 'Botswana', phone: '267' },
  { value: TCountryCode['BY'], label: 'Belarus', phone: '375' },
  { value: TCountryCode['BZ'], label: 'Belize', phone: '501' },
  {
    value: TCountryCode['CA'],
    label: 'Canada',
    phone: '1',
    suggested: true,
  },
  {
    value: TCountryCode['CC'],
    label: 'Cocos (Keeling) Islands',
    phone: '61',
  },
  {
    value: TCountryCode['CD'],
    label: 'Congo, Democratic Republic of the',
    phone: '243',
  },
  {
    value: TCountryCode['CF'],
    label: 'Central African Republic',
    phone: '236',
  },
  {
    value: TCountryCode['CG'],
    label: 'Congo, Republic of the',
    phone: '242',
  },
  { value: TCountryCode['CH'], label: 'Switzerland', phone: '41' },
  { value: TCountryCode['CI'], label: "Cote d'Ivoire", phone: '225' },
  { value: TCountryCode['CK'], label: 'Cook Islands', phone: '682' },
  { value: TCountryCode['CL'], label: 'Chile', phone: '56' },
  { value: TCountryCode['CM'], label: 'Cameroon', phone: '237' },
  { value: TCountryCode['CN'], label: 'China', phone: '86' },
  { value: TCountryCode['CO'], label: 'Colombia', phone: '57' },
  { value: TCountryCode['CR'], label: 'Costa Rica', phone: '506' },
  { value: TCountryCode['CU'], label: 'Cuba', phone: '53' },
  { value: TCountryCode['CV'], label: 'Cape Verde', phone: '238' },
  { value: TCountryCode['CW'], label: 'Curacao', phone: '599' },
  { value: TCountryCode['CX'], label: 'Christmas Island', phone: '61' },
  { value: TCountryCode['CY'], label: 'Cyprus', phone: '357' },
  { value: TCountryCode['CZ'], label: 'Czech Republic', phone: '420' },
  {
    value: TCountryCode['DE'],
    label: 'Germany',
    phone: '49',
    suggested: true,
  },
  { value: TCountryCode['DJ'], label: 'Djibouti', phone: '253' },
  { value: TCountryCode['DK'], label: 'Denmark', phone: '45' },
  { value: TCountryCode['DM'], label: 'Dominica', phone: '1-767' },
  {
    value: TCountryCode['DO'],
    label: 'Dominican Republic',
    phone: '1-809',
  },
  { value: TCountryCode['DZ'], label: 'Algeria', phone: '213' },
  { value: TCountryCode['EC'], label: 'Ecuador', phone: '593' },
  { value: TCountryCode['EE'], label: 'Estonia', phone: '372' },
  { value: TCountryCode['EG'], label: 'Egypt', phone: '20' },
  { value: TCountryCode['EH'], label: 'Western Sahara', phone: '212' },
  { value: TCountryCode['ER'], label: 'Eritrea', phone: '291' },
  { value: TCountryCode['ES'], label: 'Spain', phone: '34' },
  { value: TCountryCode['ET'], label: 'Ethiopia', phone: '251' },
  { value: TCountryCode['FI'], label: 'Finland', phone: '358' },
  { value: TCountryCode['FJ'], label: 'Fiji', phone: '679' },
  {
    value: TCountryCode['FK'],
    label: 'Falkland Islands (Malvinas)',
    phone: '500',
  },
  {
    value: TCountryCode['FM'],
    label: 'Micronesia, Federated States of',
    phone: '691',
  },
  { value: TCountryCode['FO'], label: 'Faroe Islands', phone: '298' },
  {
    value: TCountryCode['FR'],
    label: 'France',
    phone: '33',
    suggested: true,
  },
  { value: TCountryCode['GA'], label: 'Gabon', phone: '241' },
  { value: TCountryCode['GB'], label: 'United Kingdom', phone: '44' },
  { value: TCountryCode['GD'], label: 'Grenada', phone: '1-473' },
  { value: TCountryCode['GE'], label: 'Georgia', phone: '995' },
  { value: TCountryCode['GF'], label: 'French Guiana', phone: '594' },
  { value: TCountryCode['GG'], label: 'Guernsey', phone: '44' },
  { value: TCountryCode['GH'], label: 'Ghana', phone: '233' },
  { value: TCountryCode['GI'], label: 'Gibraltar', phone: '350' },
  { value: TCountryCode['GL'], label: 'Greenland', phone: '299' },
  { value: TCountryCode['GM'], label: 'Gambia', phone: '220' },
  { value: TCountryCode['GN'], label: 'Guinea', phone: '224' },
  { value: TCountryCode['GP'], label: 'Guadeloupe', phone: '590' },
  { value: TCountryCode['GQ'], label: 'Equatorial Guinea', phone: '240' },
  { value: TCountryCode['GR'], label: 'Greece', phone: '30' },
  {
    value: TCountryCode['GS'],
    label: 'South Georgia and the South Sandwich Islands',
    phone: '500',
  },
  { value: TCountryCode['GT'], label: 'Guatemala', phone: '502' },
  { value: TCountryCode['GU'], label: 'Guam', phone: '1-671' },
  { value: TCountryCode['GW'], label: 'Guinea-Bissau', phone: '245' },
  { value: TCountryCode['GY'], label: 'Guyana', phone: '592' },
  { value: TCountryCode['HK'], label: 'Hong Kong', phone: '852' },
  {
    value: TCountryCode['HM'],
    label: 'Heard Island and McDonald Islands',
    phone: '672',
  },
  { value: TCountryCode['HN'], label: 'Honduras', phone: '504' },
  { value: TCountryCode['HR'], label: 'Croatia', phone: '385' },
  { value: TCountryCode['HT'], label: 'Haiti', phone: '509' },
  { value: TCountryCode['HU'], label: 'Hungary', phone: '36' },
  { value: TCountryCode['ID'], label: 'Indonesia', phone: '62' },
  { value: TCountryCode['IE'], label: 'Ireland', phone: '353' },
  { value: TCountryCode['IL'], label: 'Israel', phone: '972' },
  { value: TCountryCode['IM'], label: 'Isle of Man', phone: '44' },
  { value: TCountryCode['IN'], label: 'India', phone: '91' },
  {
    value: TCountryCode['IO'],
    label: 'British Indian Ocean Territory',
    phone: '246',
  },
  { value: TCountryCode['IQ'], label: 'Iraq', phone: '964' },
  {
    value: TCountryCode['IR'],
    label: 'Iran, Islamic Republic of',
    phone: '98',
  },
  { value: TCountryCode['IS'], label: 'Iceland', phone: '354' },
  { value: TCountryCode['IT'], label: 'Italy', phone: '39' },
  { value: TCountryCode['JE'], label: 'Jersey', phone: '44' },
  { value: TCountryCode['JM'], label: 'Jamaica', phone: '1-876' },
  { value: TCountryCode['JO'], label: 'Jordan', phone: '962' },
  {
    value: TCountryCode['JP'],
    label: 'Japan',
    phone: '81',
    suggested: true,
  },
  { value: TCountryCode['KE'], label: 'Kenya', phone: '254' },
  { value: TCountryCode['KG'], label: 'Kyrgyzstan', phone: '996' },
  { value: TCountryCode['KH'], label: 'Cambodia', phone: '855' },
  { value: TCountryCode['KI'], label: 'Kiribati', phone: '686' },
  { value: TCountryCode['KM'], label: 'Comoros', phone: '269' },
  {
    value: TCountryCode['KN'],
    label: 'Saint Kitts and Nevis',
    phone: '1-869',
  },
  {
    value: TCountryCode['KP'],
    label: "Korea, Democratic People's Republic of",
    phone: '850',
  },
  { value: TCountryCode['KR'], label: 'Korea, Republic of', phone: '82' },
  { value: TCountryCode['KW'], label: 'Kuwait', phone: '965' },
  { value: TCountryCode['KY'], label: 'Cayman Islands', phone: '1-345' },
  { value: TCountryCode['KZ'], label: 'Kazakhstan', phone: '7' },
  {
    value: TCountryCode['LA'],
    label: "Lao People's Democratic Republic",
    phone: '856',
  },
  { value: TCountryCode['LB'], label: 'Lebanon', phone: '961' },
  { value: TCountryCode['LC'], label: 'Saint Lucia', phone: '1-758' },
  { value: TCountryCode['LI'], label: 'Liechtenstein', phone: '423' },
  { value: TCountryCode['LK'], label: 'Sri Lanka', phone: '94' },
  { value: TCountryCode['LR'], label: 'Liberia', phone: '231' },
  { value: TCountryCode['LS'], label: 'Lesotho', phone: '266' },
  { value: TCountryCode['LT'], label: 'Lithuania', phone: '370' },
  { value: TCountryCode['LU'], label: 'Luxembourg', phone: '352' },
  { value: TCountryCode['LV'], label: 'Latvia', phone: '371' },
  { value: TCountryCode['LY'], label: 'Libya', phone: '218' },
  { value: TCountryCode['MA'], label: 'Morocco', phone: '212' },
  { value: TCountryCode['MC'], label: 'Monaco', phone: '377' },
  {
    value: TCountryCode['MD'],
    label: 'Moldova, Republic of',
    phone: '373',
  },
  { value: TCountryCode['ME'], label: 'Montenegro', phone: '382' },
  {
    value: TCountryCode['MF'],
    label: 'Saint Martin (French part)',
    phone: '590',
  },
  { value: TCountryCode['MG'], label: 'Madagascar', phone: '261' },
  { value: TCountryCode['MH'], label: 'Marshall Islands', phone: '692' },
  {
    value: TCountryCode['MK'],
    label: 'Macedonia, the Former Yugoslav Republic of',
    phone: '389',
  },
  { value: TCountryCode['ML'], label: 'Mali', phone: '223' },
  { value: TCountryCode['MM'], label: 'Myanmar', phone: '95' },
  { value: TCountryCode['MN'], label: 'Mongolia', phone: '976' },
  { value: TCountryCode['MO'], label: 'Macao', phone: '853' },
  {
    value: TCountryCode['MP'],
    label: 'Northern Mariana Islands',
    phone: '1-670',
  },
  { value: TCountryCode['MQ'], label: 'Martinique', phone: '596' },
  { value: TCountryCode['MR'], label: 'Mauritania', phone: '222' },
  { value: TCountryCode['MS'], label: 'Montserrat', phone: '1-664' },
  { value: TCountryCode['MT'], label: 'Malta', phone: '356' },
  { value: TCountryCode['MU'], label: 'Mauritius', phone: '230' },
  { value: TCountryCode['MV'], label: 'Maldives', phone: '960' },
  { value: TCountryCode['MW'], label: 'Malawi', phone: '265' },
  { value: TCountryCode['MX'], label: 'Mexico', phone: '52' },
  { value: TCountryCode['MY'], label: 'Malaysia', phone: '60' },
  { value: TCountryCode['MZ'], label: 'Mozambique', phone: '258' },
  { value: TCountryCode['NA'], label: 'Namibia', phone: '264' },
  { value: TCountryCode['NC'], label: 'New Caledonia', phone: '687' },
  { value: TCountryCode['NE'], label: 'Niger', phone: '227' },
  { value: TCountryCode['NF'], label: 'Norfolk Island', phone: '672' },
  { value: TCountryCode['NG'], label: 'Nigeria', phone: '234' },
  { value: TCountryCode['NI'], label: 'Nicaragua', phone: '505' },
  { value: TCountryCode['NL'], label: 'Netherlands', phone: '31' },
  { value: TCountryCode['NO'], label: 'Norway', phone: '47' },
  { value: TCountryCode['NP'], label: 'Nepal', phone: '977' },
  { value: TCountryCode['NR'], label: 'Nauru', phone: '674' },
  { value: TCountryCode['NU'], label: 'Niue', phone: '683' },
  { value: TCountryCode['NZ'], label: 'New Zealand', phone: '64' },
  { value: TCountryCode['OM'], label: 'Oman', phone: '968' },
  { value: TCountryCode['PA'], label: 'Panama', phone: '507' },
  { value: TCountryCode['PE'], label: 'Peru', phone: '51' },
  { value: TCountryCode['PF'], label: 'French Polynesia', phone: '689' },
  { value: TCountryCode['PG'], label: 'Papua New Guinea', phone: '675' },
  { value: TCountryCode['PH'], label: 'Philippines', phone: '63' },
  { value: TCountryCode['PK'], label: 'Pakistan', phone: '92' },
  { value: TCountryCode['PL'], label: 'Poland', phone: '48' },
  {
    value: TCountryCode['PM'],
    label: 'Saint Pierre and Miquelon',
    phone: '508',
  },
  { value: TCountryCode['PN'], label: 'Pitcairn', phone: '870' },
  { value: TCountryCode['PR'], label: 'Puerto Rico', phone: '1' },
  {
    value: TCountryCode['PS'],
    label: 'Palestine, State of',
    phone: '970',
  },
  { value: TCountryCode['PT'], label: 'Portugal', phone: '351' },
  { value: TCountryCode['PW'], label: 'Palau', phone: '680' },
  { value: TCountryCode['PY'], label: 'Paraguay', phone: '595' },
  { value: TCountryCode['QA'], label: 'Qatar', phone: '974' },
  { value: TCountryCode['RE'], label: 'Reunion', phone: '262' },
  { value: TCountryCode['RO'], label: 'Romania', phone: '40' },
  { value: TCountryCode['RS'], label: 'Serbia', phone: '381' },
  { value: TCountryCode['RU'], label: 'Russian Federation', phone: '7' },
  { value: TCountryCode['RW'], label: 'Rwanda', phone: '250' },
  { value: TCountryCode['SA'], label: 'Saudi Arabia', phone: '966' },
  { value: TCountryCode['SB'], label: 'Solomon Islands', phone: '677' },
  { value: TCountryCode['SC'], label: 'Seychelles', phone: '248' },
  { value: TCountryCode['SD'], label: 'Sudan', phone: '249' },
  { value: TCountryCode['SE'], label: 'Sweden', phone: '46' },
  { value: TCountryCode['SG'], label: 'Singapore', phone: '65' },
  { value: TCountryCode['SH'], label: 'Saint Helena', phone: '290' },
  { value: TCountryCode['SI'], label: 'Slovenia', phone: '386' },
  {
    value: TCountryCode['SJ'],
    label: 'Svalbard and Jan Mayen',
    phone: '47',
  },
  { value: TCountryCode['SK'], label: 'Slovakia', phone: '421' },
  { value: TCountryCode['SL'], label: 'Sierra Leone', phone: '232' },
  { value: TCountryCode['SM'], label: 'San Marino', phone: '378' },
  { value: TCountryCode['SN'], label: 'Senegal', phone: '221' },
  { value: TCountryCode['SO'], label: 'Somalia', phone: '252' },
  { value: TCountryCode['SR'], label: 'Suriname', phone: '597' },
  { value: TCountryCode['SS'], label: 'South Sudan', phone: '211' },
  {
    value: TCountryCode['ST'],
    label: 'Sao Tome and Principe',
    phone: '239',
  },
  { value: TCountryCode['SV'], label: 'El Salvador', phone: '503' },
  {
    value: TCountryCode['SX'],
    label: 'Sint Maarten (Dutch part)',
    phone: '1-721',
  },
  {
    value: TCountryCode['SY'],
    label: 'Syrian Arab Republic',
    phone: '963',
  },
  { value: TCountryCode['SZ'], label: 'Swaziland', phone: '268' },
  {
    value: TCountryCode['TC'],
    label: 'Turks and Caicos Islands',
    phone: '1-649',
  },
  { value: TCountryCode['TD'], label: 'Chad', phone: '235' },
  {
    value: TCountryCode['TF'],
    label: 'French Southern Territories',
    phone: '262',
  },
  { value: TCountryCode['TG'], label: 'Togo', phone: '228' },
  { value: TCountryCode['TH'], label: 'Thailand', phone: '66' },
  { value: TCountryCode['TJ'], label: 'Tajikistan', phone: '992' },
  { value: TCountryCode['TK'], label: 'Tokelau', phone: '690' },
  { value: TCountryCode['TL'], label: 'Timor-Leste', phone: '670' },
  { value: TCountryCode['TM'], label: 'Turkmenistan', phone: '993' },
  { value: TCountryCode['TN'], label: 'Tunisia', phone: '216' },
  { value: TCountryCode['TO'], label: 'Tonga', phone: '676' },
  { value: TCountryCode['TR'], label: 'Turkey', phone: '90' },
  {
    value: TCountryCode['TT'],
    label: 'Trinidad and Tobago',
    phone: '1-868',
  },
  { value: TCountryCode['TV'], label: 'Tuvalu', phone: '688' },
  {
    value: TCountryCode['TW'],
    label: 'Taiwan, Republic of China',
    phone: '886',
  },
  {
    value: TCountryCode['TZ'],
    label: 'United Republic of Tanzania',
    phone: '255',
  },
  { value: TCountryCode['UA'], label: 'Ukraine', phone: '380' },
  { value: TCountryCode['UG'], label: 'Uganda', phone: '256' },
  {
    value: TCountryCode['US'],
    label: 'United States',
    phone: '1',
    suggested: true,
  },
  { value: TCountryCode['UY'], label: 'Uruguay', phone: '598' },
  { value: TCountryCode['UZ'], label: 'Uzbekistan', phone: '998' },
  {
    value: TCountryCode['VA'],
    label: 'Holy See (Vatican City State)',
    phone: '379',
  },
  {
    value: TCountryCode['VC'],
    label: 'Saint Vincent and the Grenadines',
    phone: '1-784',
  },
  { value: TCountryCode['VE'], label: 'Venezuela', phone: '58' },
  {
    value: TCountryCode['VG'],
    label: 'British Virgin Islands',
    phone: '1-284',
  },
  {
    value: TCountryCode['VI'],
    label: 'US Virgin Islands',
    phone: '1-340',
  },
  { value: TCountryCode['VN'], label: 'Vietnam', phone: '84' },
  { value: TCountryCode['VU'], label: 'Vanuatu', phone: '678' },
  { value: TCountryCode['WF'], label: 'Wallis and Futuna', phone: '681' },
  { value: TCountryCode['WS'], label: 'Samoa', phone: '685' },
  { value: TCountryCode['XK'], label: 'Kosovo', phone: '383' },
  { value: TCountryCode['YE'], label: 'Yemen', phone: '967' },
  { value: TCountryCode['YT'], label: 'Mayotte', phone: '262' },
  { value: TCountryCode['ZA'], label: 'South Africa', phone: '27' },
  { value: TCountryCode['ZM'], label: 'Zambia', phone: '260' },
  { value: TCountryCode['ZW'], label: 'Zimbabwe', phone: '263' },
];
